version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python app.test.py
          name: Test

  deploy-job:
    docker:
      - image: kroniak/ssh-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9c:9f:c7:c8:9c:03:f2:fd:c2:40:e9:8d:01:7d:ee:0f"
      - run:
          name: Deploy over SSH
          command: |
            ssh -o "StrictHostKeyChecking=no" $SSH_USER@$SSH_HOST "cd flaskapp; ./redeploy.sh"

workflows:
  main:
    jobs:
      - build-and-test
      - deploy-job

